package com.project.api.service.exception;

import org.springframework.http.HttpStatus;

/**
 * ApiException based on https://tools.ietf.org/html/rfc7807
 * 
 * @param type  (string) - A URI reference [RFC3986] that identifies the
 * 							problem type.  This specification encourages that, when
 * 							dereferenced, it provide human-readable documentation for the
 * 							problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
 * 							this member is not present, its value is assumed to be
 * 							"about:blank".
 * 
 * @param title (string) - A short, human-readable summary of the problem
 * 							type.  It SHOULD NOT change from occurrence to occurrence of the
 * 							problem, except for purposes of localization (e.g., using
 * 							proactive content negotiation; see [RFC7231], Section 3.4).
 * 
 * @param status (number) - The HTTP status code ([RFC7231], Section 6)
 * 							generated by the origin server for this occurrence of the problem.
 * 
 * @param detail (string) - A human-readable explanation specific to this
 * 							occurrence of the problem.
 * 
 * @param instance (string) - A URI reference that identifies the specific
 * 							occurrence of the problem.  It may or may not yield further
 * 							information if dereferenced.
**/
@SuppressWarnings("serial")
public abstract class ApiException extends Exception {
	private String		type;
	private String		title;
	private HttpStatus	status;
	private String		detail;
	private String		instance;

	public ApiException(String title, HttpStatus status, String detail) {
		super(detail);
		this.title = title;
		this.status = status;
		this.detail = detail;
	}

	public String getType() {
		return type;
	}

	public String getTitle() {
		return title;
	}

	public HttpStatus getStatus() {
		return status;
	}

	public String getDetail() {
		return detail;
	}

	public String getInstance() {
		return instance;
	}

	@Override
	public String toString() {
		return "{\"type\":\"" + type + "\", \"title\":\"" + title + "\", \"status\":\"" + status.value() + "\", \"detail\":\"" + detail
				+ "\", \"instance\":\"" + instance + "\"}";
	}
}
